export const GET_USERS = 'GET_USERS'
export const POST_USERS = 'POST_USERS'

export const GET_ROOMS = 'GET_ROOMS'
export const ADD_ROOMS = 'ADD_ROOMS'
export const DELETE_ROOMS = 'DELETE_ROOMS'
export const UPDATE_ROOMS = 'UPDATE_ROOMS'

export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const ADD_CUSTOMERS = 'ADD_CUSTOMERS'
export const DELETE_CUSTOMERS = 'DELETE_CUSTOMERS'
export const UPDATE_CUSTOMERS = 'UPDATE_CUSTOMERS'

export const GET_CHECKIN = 'GET_CHECKIN'
export const ADD_ORDERS = 'ADD_ORDERS'
export const UPDATE_ORDERS = 'UPDATE_ORDERS'